{% set version = "1.1.3" %}

package:
  name: cached_path
  version: {{ version }}

source:
  url: https://github.com/allenai/cached_path/archive/refs/tags/v{{ version }}.tar.gz
  sha256: de1f5175e685eb4df3322c7a9cd0bc6118cc0884ff27e232fc96496993acab74
  patches:
      # upstream expectes the folders /tests & /test_fixtures to be relative
      # to the finished package, even though those folders are not packaged;
      # effectively, the upstream test suite can currently only be run in (their)
      # development mode, so patch it that we can properly test the package here.
    - patches/0001-patch-BaseTestClass-so-that-test-suite-can-be-run-wi.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]
  # debug this on the feedstock; allennlp stack in conda-forge
  # doesn't support windows yet anyway due to missing pytorch
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - boto3 >=1.0,<2.0
    - filelock >=3.4,<3.8
    - google-cloud-storage >=1.0,<3.0
    - huggingface_hub >=0.0.12,<0.8.0
    - requests >=2.0,<3.0
    - rich >=12.1,<13
    - tqdm >=4.62,<4.65
test:
  requires:
    - pytest
    - flaky
    - responses
  source_files:
    - test_fixtures/
    - tests/
  imports:
    - cached_path
  commands:
    - pytest -v

about:
  home: https://github.com/allenai/cached_path
  license: Apache-2.0
  license_file: LICENSE
  summary: A file utility for accessing both local and remote files through a unified interface.
  dev_url: https://github.com/allenai/cached_path
  doc_url: https://cached-path.readthedocs.io/

extra:
  recipe-maintainers:
    - h-vetinari
